### ISSUE TITLE
fontra-workflow TODO

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1144]
Actions to write:
- [ ] Instantiate
- [ ] Slice / extend axes
- [ ] Drop axes
- [ ] Warp axis (change axis values, remapping all sources to new values)
- [ ] Flatten variable components

Integration:
- [ ] Allow other packages to register actions (via entry points in pyproject.toml)
- [ ] Turn fontra-compile into an action
