### ISSUE TITLE
[avar-2] General TODO for avar-2 support

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1274]
- [ ] Data structure and backend API changes
  - Determine and implement new axes data structure
  - Adapt backend API definition to new data structure
  - Adapt the designspace backend to the new axis API, implement read/write
  - Adapt the other backends to the new axis API
  - Adapt the server and front end code to the new axis API
  - Adapt fontra-workflow to the new axis API 
- [ ] Refactor internal location mapping (avar-1) so we can add avar-2-type mapping
- [ ] Implement and test the mapping algorithm with VariationModel in JS
- [ ] Design, implement, and test location UI
- [ ] Design, implement and test basic authoring UI
