### ISSUE TITLE
Create Pen Tool

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#30]
- [x] Improve infrastructure so adding/deleting points/contours works #115
- [x] Basic pen tool to draw an open polygon #115
- [x] Close contour #137
- [x] Attach to other open contour
- [x] Drag BCP handles while adding new points #137
- ~[ ] Draw BCP handle from arbitrary point~ *defer until later*
- [x] Insert point on segment #296
- ~[ ] Alt-click switches to pointer tool (maybe redundant, as we have ”1, 2, 3” shortcuts for tool selection)~ *this is non-essential, perhaps "nice for later"*
- [x] Hover should highlight a node when something special happens when we click or drag on it

Relates to #9

**Comment by justvanrossum** [comment]
This is being implemented in #115.

**Comment by justvanrossum** [comment]
Additional work in #137
