### ISSUE TITLE
[sidebars] further cleanup and refactoring is needed

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#748]
- [x] Panels need to be notified when they are shown or hidden, so they can respond to that (Done in #757)
- [ ] There is still some init/setup code of individual panels left in editor.js, that should be moved to the respective panel classes (mostly done in #757, the rest is blocked by a missing feature: #766)
- [x] Rethink the `attach()` method (#934)
- [x] The various panels should ideally more consistent in how their construction/setup is coded (#934)

All this is needed for better future extensibility and use by plugins.

**Comment by justvanrossum** [comment]
Now that #766/#935 is done, and after #934 is completed, we can continue with this issue.

Most notably, the following snippet should be moved to panel-glyph-search.js:

https://github.com/googlefonts/fontra/blob/d64caafaba697cee96c3ac2df6e3b1fa3c8fe825/src/fontra/views/editor/editor.js#L301-L315
