### ISSUE TITLE
Get/view/edit project-wide font info

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#907]
Relates to #54, font info + global axes can be part of the same UI (a new "view")

- [x] Family-level Font Info (names, copyright, version, upm) #1217
- [x] Font Axes editor #1063
- [x] Font Sources editor #1411
